
namespace android {
....
....
....
int register_com_android_server_sensortask_SensorTaskService(JNIEnv* env);
};

extern "C" jint JNI_OnLoad(JavaVM* vm, void* /* reserved */)
{
....
....
....
    // register_com_android_server_sensortask_SensorTaskService(env);
    return JNI_VERSION_1_4;
}